
prompt_in_dir = "D:/Andrew/Pictures/==train/t32.TXT"

img_in_dir = 'O:/==IMGOPS/in'
img_out_dir = 'O:/==IMGOPS/out'
img_save_dir = "O:/==IMGOPS/save"

# prompt settings
[prompt]
start_tags = "best quality"
end_tags = ""
vital_tags = ""

# tag expansion
[inference]
lstm_model_path = "extensions/tag_expansion/tag_expansion_model_epoch220.pth"
lstm_vocab_path = "extensions/tag_expansion/vocab.json"
